# Generated by Django 3.2.7 on 2021-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AlterField(
            model_name='voter',
            name='adhar',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
