# Generated by Django 3.2.7 on 2021-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_auto_20211122_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
