# Generated by Django 4.0.1 on 2022-05-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20211123_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='adhar_photo',
            field=models.ImageField(upload_to='images/adhar'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='profile_photo',
            field=models.ImageField(upload_to='images/profile'),
        ),
    ]
