# Generated by Django 3.2.7 on 2021-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('adhar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
        ),
    ]
