# Generated by Django 3.2.7 on 2021-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votingpoll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_name', models.CharField(max_length=50)),
                ('voting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('result_date', models.DateField()),
                ('result_time', models.TimeField()),
            ],
        ),
    ]
