# Generated by Django 4.0.1 on 2022-05-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_result_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voted',
            old_name='poling_id',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='voted',
            old_name='adhar',
            new_name='voter_adhar',
        ),
    ]
