# Generated by Django 4.0.1 on 2022-05-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_alter_voter_adhar_photo_alter_voter_profile_photo'),
        ('voting', '0004_rename_poling_id_voted_poll_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted',
            name='voter_adhar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voter'),
        ),
    ]
