# Generated by Django 3.2.7 on 2021-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('adhar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('profile_photo', models.ImageField(upload_to='media/images/profile')),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adhar_photo', models.ImageField(upload_to='media/images/adhar')),
                ('symbol_photo', models.ImageField(upload_to='media/images/symbol')),
            ],
        ),
    ]
